server:
  port: 8888

#conf : /Users/jlong/Desktop/microservices-lab-configuration

spring:
  cloud:
    config:
      server:
        git :
          uri:  ${conf:https://github.com/joshlong/microservices-lab-configuration}
