server:
  port: 9000

zuul:
  proxy:
    mapping: /api
    addProxyHeaders: true
    route:
      reviews-service: /reviews
      catalog-service: /catalog
      recommendations-service: /recommendations

